#!/bin/bash
## The following comment lines are PBS resour
#PBS -q shared
#PBS -l walltime=120
#PBS -e out/run_shel.err
#PBS -o out/run_shel.out

# abort on error:
set -eu 

# Go to directory:
cd ${PBS_O_WORKDIR}

# link in the correct *.dev input files
ln -sf inp/ww3_shel.inp ./
mv out/mod_def.ww3 ./

# export OMP_NUM_THREADS=4

# run the ww3_grid program
# /home/d03/lsampson/GPU_Hacka/OMP_F90/ww3_shel
/home/d03/lsampson/GPU_Hacka/SEQ_F90/ww3_shel
mv *.ww3 out/
