#!/bin/bash
## The following comment lines are PBS resource requests:
#PBS -q pascalq
#PBS -l ncpus=1
#PBS -l walltime=120
#PBS -e out/run_grid.err
#PBS -o out/run_grid.out

set -eu

#cd ${PBS_O_WORKDIR}  #May be required for qsub jobs
mkdir -p out/

## link in the correct *.dev input files:
ln -sf inp/ww3_grid.nml ./

## run the ww3_grid program:
#../OMP_F90/ww3_grid
../SEQ_F90/ww3_grid

mv mod_def.ww3 out/
