#!/bin/bash
## The following comment lines are PBS resource requests:
#PBS -q pascalq
#PBS -l ncpus=1
#PBS -l walltime=120
#PBS -e out/run_all.err
#PBS -o out/run_all.out

## run the ww3_grid program:
## link in the correct *.dev input files:
ln -sf inp/ww3_grid.nml ./

#../OMP_F90/ww3_grid
../SEQ_F90/ww3_grid

## run the ww3_shel program:
ln -sf inp/ww3_shel.inp ./
export OMP_NUM_THREADS=1

#../OMP_F90/ww3_shel
../SEQ_F90/ww3_shel

## run the ww3_outf program:

ln -sf inp/ww3_outf.inp ./
#../OMP_F90/ww3_outf
../SEQ_F90/ww3_outf

mv *.ww3 out/
mkdir -p out/ww3_outf/
rm -rf out/ww3_outf/*
mv ww3.* out/ww3_outf/

differences=$(diff -q -U 0 out/checking_outf/ out/ww3_outf/ | grep -v ^@ | wc -l)

if [ $differences != 0 ]
then
    echo "There are $differences different lines between checking_outf and ww3_outf."
else
    echo "There are no differences between checking_outf and this run."
fi

