#!/bin/bash
## The following comment lines are PBS resource requests:
#PBS -l select=1:ncpus=1
#PBS -q pascalq 
#PBS -l walltime=120
#PBS -o out/run_outf.out
#PBS -e out/run_outf.err
set -eu

## Change directory to where job was submitted:
cd ${PBS_O_WORKDIR:-.}

## link in the correct input files:
ln -sf inp/ww3_outf.inp ./

mv out/*.ww3 ./

## run the ww3_shel program:
#../OMP_F90/ww3_outf
../SEQ_F90/ww3_outf

mv *.ww3 out/
mkdir -p out/ww3_outf/
rm -rf out/ww3_outf/*
mv ww3.* out/ww3_outf/

differences=$(diff -q -U 0 out/checking_outf/ out/ww3_outf/ | grep -v ^@ | wc -l)

if [ $differences != 0 ]
then
    echo "There are $differences different lines between checking_outf and ww3_outf."
else
    echo "There are no differences between checking_outf and this run."
fi

# Run 'tail -1 out/run_outf.out' afterwards to print the final output.
