#!/bin/bash
## The following comment lines are PBS resource requests:
#PBS -q shared
#PBS -l walltime=120
#PBS -e out/run_grid.err
#PBS -o out/run_grid.out

# abort on error:
set -eu 

# Go to directory:
cd ${PBS_O_WORKDIR}

# link in the correct *.dev input files
ln -sf inp/ww3_grid.nml ./

# run the ww3_grid program:
/home/d03/lsampson/GPU_Hacka/SEQ_F90/ww3_grid

mv mod_def.ww3 out/
